spring:
  application:
    name: @project.artifactId@
info:
  version: @project.version@
server:
  port: 7000
management:
  endpoint:
    health:
      # 测试使用，正式环境需要配置成 when_authorized
      show-details: always
  endpoints:
    web:
      exposure:
        # 测试使用 - 开放所有端口
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
